name: Sequential Jobs
on:
  push:
    branches:
      - main
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First Job Action
        run: echo "First Job Complete"
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: Second Job Action
        run: echo "Second Job Complete"
